version: "3.9"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
      - "8080:8080"
      - "8070:8070"
      - "8090:8090"
      - "11:11"
      - "1111:1111"
